//
//  OperationTypeEnum.h
//  APIMATICCalculator
//
//  This file was automatically generated by APIMATIC BETA v2.0 on 02/12/2016
//
#ifndef APIMATIC_OPERATIONTYPEENUMHELPER
#define APIMATIC_OPERATIONTYPEENUMHELPER

#include "OperationTypeEnum.h"

/**
* Helper class interface for OperationTypeEnum to NSString conversion
*/
@interface OperationTypeEnumHelper : NSObject

+(id) stringFromOperationTypeEnum:(enum OperationTypeEnum) operationTypeEnum withDefault: (id) defaultValue;

+(enum OperationTypeEnum) operationTypeEnumFromString:(NSString*) strValue;

@end

#endif