//
//  OperationTypeEnum.h
//  APIMATICCalculator
//
//  This file was automatically generated by APIMATIC BETA v2.0 on 02/12/2016
//
#ifndef APIMATIC_OPERATIONTYPEENUM
#define APIMATIC_OPERATIONTYPEENUM
 
enum OperationTypeEnum
{
        OperationTypeSUM, //Represents the sum operator
        OperationTypeSUBTRACT, //Represents the subtract operator
        OperationTypeMULTIPLY, //Represents the multiply operator
        OperationTypeDIVIDE, //Represents the divide operator
};

#endif