//
//  OperationTypeEnum.h
//  APIMATICCalculator
//
//  This file was automatically generated by APIMATIC BETA v2.0 on 02/12/2016
//
#include "OperationTypeEnumHelper.h"

/**
* Helper class implementation for OperationTypeEnum to NSString conversion
*/
@implementation OperationTypeEnumHelper

+(id) stringFromOperationTypeEnum:(enum OperationTypeEnum) operationTypeEnum withDefault: (id) defaultValue
{
    switch(operationTypeEnum)
    {
        case OperationTypeSUM:
            return @"SUM";

        case OperationTypeSUBTRACT:
            return @"SUBTRACT";

        case OperationTypeMULTIPLY:
            return @"MULTIPLY";

        case OperationTypeDIVIDE:
            return @"DIVIDE";

        default:
            return defaultValue;
    }
}

+(enum OperationTypeEnum) operationTypeEnumFromString:(NSString*) strValue
{
    NSArray* OperationTypeEnumArray = [NSArray arrayWithObjects:
                                        @"SUM",
                                        @"SUBTRACT",
                                        @"MULTIPLY",
                                        @"DIVIDE",
                                        nil];

    return (enum OperationTypeEnum) [OperationTypeEnumArray indexOfObject: strValue];
}

@end