//
//  SimpleCalculatorController.h
//  APIMATICCalculator
//
//  This file was automatically generated by APIMATIC BETA v2.0 on 02/12/2016
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "OperationTypeEnum.h"
#import "OperationTypeEnumHelper.h"
#import "GetCalculateInput.h"

@interface SimpleCalculatorController : BaseController

/**
* Completion block definition for asynchronous call to Calculate */
typedef void (^CompletedGetCalculate)(BOOL success, HttpContext* context, NSNumber* response, NSError* error);

/**
* Calculates the expression using the specified operation.
* @param  GetCalculateInput     Object with all parameters
*/
- (void) getCalculateAsyncWithGetCalculateInput:(GetCalculateInput*) input
                completionBlock:(CompletedGetCalculate) onCompleted;

@end