//
//  Configuration.m
//  APIMATICCalculator
//
//  This file was automatically generated by APIMATIC BETA v2.0 on 02/12/2016
//
#import "Configuration.h"

/** The base Uri for API calls */
NSString* Configuration_BaseUri = @"https://examples.apimatic.io/apps/calculator";

