//
//  Configuration.h
//  APIMATICCalculator
//
//  This file was automatically generated by APIMATIC BETA v2.0 on 02/12/2016
//
#ifndef APIMATICCalculator_Configuration_h
#define APIMATICCalculator_Configuration_h

/** The base Uri for API calls */
extern NSString* Configuration_BaseUri;

#endif
